--- #YAML:1.0
name:               Vimpl
version:            0.02
abstract:           For managing your Vim scripts with Pathogen.vim and Git.
author:
    - Colin Kennedy <moshen@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:  0
    Data::Dumper:      0
    File::Copy:        0
    File::Path:        0
    JSON::XS:          0
    LWP::UserAgent:    0
    MIME::Base64:      0
    Pod::Usage:        0
    Test::More:        0
    Web::Scraper:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
